export const CITY_ADDED = 'CITY_ADDED';
export const CITY_REMOVED = 'CITY_REMOVED';
export const FETCH_WEATHER_DATA_STARTED = 'FETCH_WEATHER_DATA_STARTED';
export const WEATHER_DATA_RECEIVED = 'WEATHER_DATA_RECEIVED';
export const FETCH_WEATHER_DATA_FINISHED = 'FETCH_WEATHER_DATA_FINISHED';
export const FETCH_WEATHER_DATA_FAILED = 'FETCH_WEATHER_DATA_FAILED';